### ISSUE TITLE
Use front camera by default

### ISSUE THREAD

**Issue by jperocho** [kmturley/cordova-plugin-media-custom#1]
Hello kmturley,

How do you set it to use front camera?

**Comment by kmturley** [comment]
At the moment there isn't a way to select the Camera via Javascript. But you can change it in Java and recompile the plugin:

https://github.com/kmturley/cordova-plugin-media-custom/blob/master/src/android/Camera2VideoFragment.java#L369

```
String cameraId = manager.getCameraIdList()[0]; // 0 - back camera
String cameraId = manager.getCameraIdList()[1]; // 1 - front camera
```

I will plan on adding this as a feature!

**Comment by jperocho** [comment]
Big thanks for the Java tip, Nice to see this enhancement to be added in the future. Thanks again!
