### ISSUE TITLE
Could not add the plugin following the Readme

### ISSUE THREAD

**Issue by martinberlin** [kmturley/cordova-plugin-media-custom#2]
Hello and thanks for this great plugin, I would love to try it out, followed:
https://github.com/kmturley/cordova-plugin-media-custom#installation-and-running-tasks

     $ cordova plugin add cordova-plugin-media-custom
     npm: Command failed with exit code 1 Error output:
     npm ERR! code E404
     npm ERR! 404 'cordova-plugin-media-custom' is not in the npm registry.

I though giving the github path could work, but instead I get a different error:

     cordova plugin add https://github.com/kmturley/cordova-plugin-media-custom.git
     Failed to fetch plugin https://github.com/kmturley/cordova-plugin-media-custom.git via registry.
     Probably this is either a connection problem, or plugin spec is incorrect.
     Check your connection and plugin name/version/URL.
     Error: npm: Command failed with exit code 1 Error output:
     npm ERR! premature close

Found here the solution:
https://github.com/jiveabillion/cordova-plugin-media-custom

It seems that new cordova needs package.json instead of plugin.json a pity he didn't made a pull request. Thanks for fixing!

**Comment by kmturley** [comment]
Looks like they've changed the plugin spec:
https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html

They now require a `package.json` instead of a `plugin.json`:
```
npm install -g plugman
plugman createpackagejson /path/to/your/plugin
```

Will update to match, and ensure it's published to npm!

**Comment by kmturley** [comment]
And published to:
https://www.npmjs.com/package/cordova-plugin-media-custom

Thanks for flagging the issue!
